---
language: node_js
node_js: lts/erbium
sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

env:
  global:
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    - stage: "Tests"
      before_install:
        - npm config set spin false
        - npm install -g codecov
        - npm install -g @commitlint/travis-cli
        - yarn --version
      script:
        - commitlint-travis
        - yarn lint:js
        - yarn lint:hbs
        - yarn test
      after_success:
        - codecov --file=coverage/lcov.info

    - stage: "Regression Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic

    - stage: "Release"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

before_install:
  - npm config set spin false
  - yarn --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

stages:
  - "Tests"
  - "Regression Tests"
  - name: "Release"
    if: branch = master

